# Generated by Django 4.2 on 2023-05-14 10:46

from django.db import migrations, models
import tools.file_converter.models
import tools.file_converter.validators


class Migration(migrations.Migration):

    dependencies = [
        ("file_converter", "0002_rename_fileconverter_fileconversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileconversion",
            name="input_file",
            field=models.FileField(
                upload_to=tools.file_converter.models.user_directory_path,
                validators=[
                    tools.file_converter.validators.FileValidator(
                        content_types=[
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "text/html",
                            "application/vnd.oasis.opendocument.text",
                            "application/pdf",
                            "application/vnd.ms-powerpoint",
                            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                            "application/rtf",
                            "text/plain",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "application/pdf",
                        ],
                        max_size=100000000,
                        min_size=100,
                    )
                ],
            ),
        ),
    ]
