# Generated by Django 4.2 on 2023-05-22 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.file_converter.models
import tools.file_converter.mystorage
import tools.file_converter.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_converter", "0003_alter_fileconversion_input_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileconversion",
            name="input_file",
            field=models.FileField(
                storage=tools.file_converter.mystorage.CleanFileNameStorage(),
                unique=True,
                upload_to=tools.file_converter.models.user_directory_path,
                validators=[
                    tools.file_converter.validators.FileValidator(
                        content_types=[
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "text/html",
                            "application/vnd.oasis.opendocument.text",
                            "application/pdf",
                            "application/vnd.ms-powerpoint",
                            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                            "application/rtf",
                            "text/plain",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            "application/pdf",
                        ],
                        max_size=100000000,
                        min_size=100,
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="fileconversion",
            name="output_file",
            field=models.FileField(
                unique=True, upload_to=tools.file_converter.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="fileconversion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
