name: Python Code Formatting

on:
  push:

jobs:
  format:
    name: Format Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Format Python code
        run: black **/*.py  # Format all Python files

      - name: Commit changes
        run: |
          git config --global user.name "Aidan Comer"
          git config --global user.email "alhcomer@hotmail.co.uk"
          git add .
          git commit -m "Apply Black code formatting" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}