name: Python Code Formatter

on:
  push:
    branches:
      - main

jobs:
  format:
    name: Format Python Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5

    - name: Install dependencies
      run: pip install black

    - name: Run Black formatter
      run: black .

    - name: Commit changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add .
        git commit -m "Apply Black formatting"
        git push
