name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.5
    - name: Update Pylint
      run: pip install --upgrade pylint
    - name: Syntax check
      run: python -m compileall tools_website
    - name: Analysing the code with pylint
      run: |
        find tools_website -type f -name "*.py" -print0 | xargs -0 pylint
